server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update # позже поставлю none, и поставлю sql-миграции
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/habitflow
    username: habitflow
#   password: habitflow - TOLEARN #5 Это то что должно лежать в Vault. По фану сделал так
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/habitflow
